In [2]:
from scipy import sparse
from scipy import linalg
import numpy as np
import pandas as pd

In [8]:
arr = [ [0.0, 0.8, 0.6, 0.1, 0.0, 0.0], 
        [0.8, 0.0, 0.9, 0.0, 0.0, 0.0], 
        [0.6, 0.9, 0.0, 0.0, 0.0, 0.2], 
        [0.1, 0.0, 0.0, 0.0, 0.6, 0.7], 
        [0.0, 0.0, 0.0, 0.6, 0.0, 0.8], 
        [0.0, 0.0, 0.2, 0.7, 0.8, 0.0]]
arr = np.array(arr)
print(arr)
LaplacianMatrix = sparse.csgraph.laplacian(csgraph=arr, normed=False)
print(LaplacianMatrix)

[[0.  0.8 0.6 0.1 0.  0. ]
 [0.8 0.  0.9 0.  0.  0. ]
 [0.6 0.9 0.  0.  0.  0.2]
 [0.1 0.  0.  0.  0.6 0.7]
 [0.  0.  0.  0.6 0.  0.8]
 [0.  0.  0.2 0.7 0.8 0. ]]
[[ 1.5 -0.8 -0.6 -0.1 -0.  -0. ]
 [-0.8  1.7 -0.9 -0.  -0.  -0. ]
 [-0.6 -0.9  1.7 -0.  -0.  -0.2]
 [-0.1 -0.  -0.   1.4 -0.6 -0.7]
 [-0.  -0.  -0.  -0.6  1.4 -0.8]
 [-0.  -0.  -0.2 -0.7 -0.8  1.7]]


In [9]:
eigenvalue, eigenvector = linalg.eig(LaplacianMatrix)
eigenvalue = np.real(eigenvalue)
df = pd.DataFrame(data = eigenvector, index = eigenvalue)
df = df.round(3)
df.index = df.index.to_series().round(3)
print(df)

           0      1      2      3      4      5
0.000  0.408  0.408 -0.291 -0.643 -0.149  0.383
0.189  0.408  0.439  0.085  0.110  0.686 -0.388
1.963  0.408  0.374  0.233  0.517 -0.609 -0.026
2.147  0.408 -0.403 -0.737  0.182 -0.090 -0.295
2.673  0.408 -0.446  0.527 -0.444 -0.160 -0.367
2.429  0.408 -0.373  0.182  0.278  0.321  0.693
